---
name: misspell

on:
  # https://github.community/t/workflow-with-on-push-triggers-on-release/17414
  push:
    branches:
      - '**'
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '.github/workflows/**'

jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1
      - name: misspell
        if: ${{ !env.ACT }}
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
          reporter: github-check  # Change reporter.
