# https://github.com/marketplace/actions/upload-files-to-a-github-release
# get commit messages between current and previous tag:
# - git log --pretty="%h - %s (%an)" "$(git describe --abbrev=0 --tags "$(git describe --tags --abbrev=0)^")...$(git describe --tags --abbrev=0)"

name: Release Binaries

on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
  release:
    types: [created]

jobs:
  pub_wheel:
    name: Publish Wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3
      - name: Install build tools
        run: pip install setuptools wheel build
      - name: Install requirements
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: build
        run: python -m build
      - name: Get Wheel File Path
        id: getwheelfile
        shell: bash
        run: echo "::set-output name=wheelfile::$(find "dist" -type f -name "*.whl" | cut -d "/" -f2-)"
      - name: Test pip install of wheel
        shell: bash
        run: pip install $(find "dist" -type f -name "*.whl")
      - name: Test python import
        shell: bash
        run: python -c "import file_metadata"
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/${{ steps.getwheelfile.outputs.wheelfile }}
          asset_name: ${{ steps.getwheelfile.outputs.wheelfile }}
          tag: ${{ github.ref }}
  publish:
    # needs: pub_wheel
    name: Release Binary for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: file_metadata
            asset_name: file_metadata-${{ github.ref }}-linux-amd64.zip
          - os: windows-latest
            artifact_name: file_metadata.exe
            asset_name: file_metadata-${{ github.ref }}-windows-amd64.zip
          - os: macos-latest
            artifact_name: file_metadata
            asset_name: file_metadata-${{ github.ref }}-macos-amd64.zip
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3
      - name: Install build tools
        run: pip install setuptools wheel build pyinstaller
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: pyinstaller build binary
        run: python ./versionfile.py; pyinstaller ./file_metadata.py --clean --onefile --version-file=versionfile.txt
      # https://github.com/marketplace/actions/easy-zip-files
      - uses: papeloto/action-zip@v1
        with:
          files: ./dist/${{ matrix.artifact_name }}
          dest: ./dist/file_metadata.zip
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/file_metadata.zip
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
