---
name: test_tmp

on: push

jobs:
  test_tmp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Test run
        shell: bash
        # git fetch --all --tags
        run: |
          git tag -l --sort=-version:refname | head -n 1
          git tag -l --sort=-version:refname | head -n 2 | tail -n 1
          git log --pretty="%h - %s (%an)" $(git tag -l --sort=-version:refname | head -n 2 | tail -n 1)...$(git tag -l --sort=-version:refname | head -n 1) > _release_notes.md
          cat _release_notes.md
